<a href="https://colab.research.google.com/github/advik-7/NLP_projects/blob/main/RNN_text_prediction_trained.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install python-docx


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.3/244.3 kB 4.5 MB/s eta 0:00:00


In [2]:
from docx import Document

# Open the .docx file
doc = Document('/content/moby_dick_ch4.docx')

# Read the content
for paragraph in doc.paragraphs:
    print(paragraph.text)


Upon waking next morning about daylight, I found Queequeg's arm thrown over me in the most loving and affectionate manner. You had almost thought I had been his wife. The counterpane was of patchwork, full of odd little parti-coloured squares and triangles; and this arm of his tattooed all over with an interminable Cretan labyrinth of a figure, no two parts of which were of one precise shade--owing I suppose to his keeping his arm at sea unmethodically in sun and shade, his shirt sleeves irregularly rolled up at various times--this same arm of his, I say, looked for all the world like a strip of that same patchwork quilt. Indeed, partly lying on it as the arm did when I first awoke, I could hardly tell it from the quilt, they so blended their hues together; and it was only by the sense of weight and pressure that I could tell that Queequeg was hugging me.
My sensations were strange. Let me try to explain them. When I was a child, I well remember a somewhat similar circumstance that bef

In [3]:
import spacy
nlp = spacy.load("en_core_web_sm",disable=['parser','tagger','ner'])

In [4]:
nlp.max_length

1000000

In [5]:
def read_docx(file_path):
    """
    Function to read text from a .docx file.

    Returns:
    str: Text extracted from the .docx file.
    """
    doc =Document(file_path)
    full_text= []
    for para in doc.paragraphs:
        full_text.append(para.text)
    return '\n'.join(full_text)
data = read_docx("/content/moby_dick_ch4.docx")

In [6]:
def sep_pun(doc_text):
  return [token.text.lower() for token in nlp.doc]

In [7]:
import re

def filter_special_characters(tokens):
    """
    Function to filter out special characters and punctuation from a list of tokens.

    Args:
    tokens (list of str): List of tokens.

    Returns:
    list of str: List of tokens with special characters and punctuation removed.
    """
    filtered_tokens = []
    for token in tokens:
        # Remove any character that is not a letter or a digit
        cleaned_token = re.sub(r'[^a-zA-Z0-9]', '', token)
        if cleaned_token:  # Only add non-empty tokens
            filtered_tokens.append(cleaned_token)
    return filtered_tokens

# Example usage
tokens = ["hello,", "world!", "#NLP", "is", "fun.", "123", "@AI"]
filtered_tokens = filter_special_characters(tokens)
print(filtered_tokens)


['hello', 'world', 'NLP', 'is', 'fun', '123', 'AI']


In [8]:
def filter_special_characters(tokens):
    filtered_tokens = []
    for token in tokens:
        cleaned_token = re.sub(r'[^a-zA-Z0-9]', '', token.text)
        if cleaned_token:  # Only add non-empty tokens
            filtered_tokens.append(cleaned_token)
    return filtered_tokens

In [9]:
text=nlp(data)

/usr/local/lib/python3.10/dist-packages/spacy/pipeline/lemmatizer.py:211: UserWarning: [W108] The rule-based lemmatizer did not find POS annotation for one or more tokens. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
  warnings.warn(Warnings.W108)


In [10]:
tokens=filter_special_characters(text)

In [11]:
vocab_size=len(tokens)
vocab_size

1670

In [12]:
train_length=25+1
train_sequence=[]
for i in range(train_length,len(tokens)):
  seq=tokens[i-train_length:i]
  train_sequence.append(seq)


In [13]:
type(train_sequence)

list

In [14]:
train_sequence[0]

['Upon',
 'waking',
 'next',
 'morning',
 'about',
 'daylight',
 'I',
 'found',
 'Queequeg',
 's',
 'arm',
 'thrown',
 'over',
 'me',
 'in',
 'the',
 'most',
 'loving',
 'and',
 'affectionate',
 'manner',
 'You',
 'had',
 'almost',
 'thought',
 'I']

In [16]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [17]:
tokenizer=Tokenizer()

In [18]:
tokenizer.fit_on_texts(train_sequence)

In [19]:
sequences=tokenizer.texts_to_sequences
seq=sequences(train_sequence)

In [20]:
tokenizer.index_word

{1: 'the',
 2: 'and',
 3: 'i',
 4: 'a',
 5: 'to',
 6: 'his',
 7: 'of',
 8: 'in',
 9: 'was',
 10: 'he',
 11: 'it',
 12: 'at',
 13: 'me',
 14: 'as',
 15: 'my',
 16: 'but',
 17: 'that',
 18: 'up',
 19: 'with',
 20: 'by',
 21: 'queequeg',
 22: 'all',
 23: 'for',
 24: 'not',
 25: 'this',
 26: 'on',
 27: 'bed',
 28: 'arm',
 29: 'were',
 30: 'from',
 31: 'if',
 32: 'over',
 33: 'when',
 34: 'there',
 35: 'very',
 36: 'then',
 37: 'had',
 38: 'could',
 39: 'so',
 40: 'or',
 41: 'lay',
 42: 'have',
 43: 'himself',
 44: 'is',
 45: 'boots',
 46: 'room',
 47: 'little',
 48: 'no',
 49: 'one',
 50: 'time',
 51: 'though',
 52: 'myself',
 53: 'last',
 54: 'now',
 55: 'be',
 56: 'hand',
 57: 'seemed',
 58: 'would',
 59: 'him',
 60: 'out',
 61: 's',
 62: 'been',
 63: 'an',
 64: 'only',
 65: 'felt',
 66: 'into',
 67: 'what',
 68: 'how',
 69: 'much',
 70: 'made',
 71: 'under',
 72: 'hat',
 73: 'you',
 74: 'great',
 75: 'about',
 76: 'morning',
 77: 'like',
 78: 'waking',
 79: 'upon',
 80: 'counterpane',
 

In [21]:
len(tokenizer.word_counts)

659

In [22]:
import numpy as np

In [23]:
sequences

<bound method Tokenizer.texts_to_sequences of <keras.src.legacy.preprocessing.text.Tokenizer object at 0x7c61dc34fac0>>

In [24]:
seq=np.array(seq)

In [25]:
print(seq)

[[ 79  78 195 ... 647 192   3]
 [ 78 195  76 ... 192   3  37]
 [195  76  75 ...   3  37  62]
 ...
 [185   9 186 ... 107  77   4]
 [  9 186 646 ...  77   4 659]
 [186 646   2 ...   4 659  61]]


In [26]:
X = seq[:,:-1]
Y = seq[:,-1]

In [27]:
seq_length=X.shape

In [28]:
from tensorflow.keras.utils import to_categorical

In [29]:
Y=to_categorical(Y)

In [30]:
from tensorflow import keras

In [31]:
from keras.models import Sequential

In [32]:

from keras.layers import Dense,LSTM,Embedding

In [33]:

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import CategoricalCrossentropy

In [34]:
len(X)

1644

In [45]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.optimizers import Adam

def create_model(vocabulary_size, sequence_length, embedding_dim):
    model = Sequential()
    model.add(Embedding(input_dim=vocabulary_size, output_dim=embedding_dim, input_length=sequence_length))
    model.add(LSTM(50, return_sequences=True))
    model.add(LSTM(50))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(vocabulary_size, activation='softmax'))
    model.compile(loss=CategoricalCrossentropy(), optimizer=Adam(), metrics=['accuracy'])
    model.summary()
    return model




In [46]:
X.shape

(1644, 25)

In [47]:
seq_length

(1644, 25)

In [48]:
sequence_length=X.shape[1]

In [49]:
X.shape

(1644, 25)

In [50]:
Y.shape

(1644, 660)

In [51]:
len(tokenizer.word_counts)

659

In [52]:
vocabulary_size=len(tokenizer.word_counts)

In [53]:
model=create_model(vocabulary_size+1,sequence_length,50)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_2 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_3 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [54]:
from pickle import dump,load

In [59]:
model.fit(X,Y,batch_size=128,epochs=50,verbose=1)

Epoch 1/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - accuracy: 0.9179 - loss: 0.3746
Epoch 2/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step - accuracy: 0.9089 - loss: 0.3661
Epoch 3/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - accuracy: 0.9149 - loss: 0.3776
Epoch 4/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.9165 - loss: 0.3535
Epoch 5/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - accuracy: 0.9289 - loss: 0.3162
Epoch 6/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9370 - loss: 0.3096
Epoch 7/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.9259 - loss: 0.3315
Epoch 8/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 76ms/step - accuracy: 0.9248 - loss: 0.3249
Epoch 9/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - accuracy: 0.9233 - loss: 0.3189
Epoch 10/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 85ms/step - accuracy: 0.9449 - loss: 0.2759
Epoch 11/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - accuracy: 0.9452 - loss: 0.2534
Epoch 12/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy:

In [63]:

model.save_weights('moby_dick_ch4.weights.h5')


In [64]:

model.save('RNN_T_Moby_dick.h5')


In [80]:
def predict_next_word(model, tokenizer, text, max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    return tokenizer.index_word[predicted[0]]

seed_text = "Once upon a time"
next_word = predict_next_word(model, tokenizer, seed_text, max_sequence_len)
print(f"Next word prediction: {next_word}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
Next word prediction: were
